version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: aireq-postgres
    environment:
      POSTGRES_DB: aireqgen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aireq-app:
    image: aireq
    container_name: aireq-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aireqgen
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
